### PR TITLE
Converting static modules to dynamic modules.

### PR DESCRIPTION
**Pull request by CHERTS**

### CODE REVIEW

**Comment by Leryan** [comment]
This feature in available only from nginx 1.9.11, i would recommend to let the possibility to statically build the module, for compatibility with older versions, like the current stable one.

**Comment by falzm** [comment]
Could you please merge this PR? It'd be nice to build your module as dynamic module and package it individually for Debian/Ubuntu.

**Comment by kabili207** [comment]
It looks like this pull request removes the checks for *nix systems and also removes support for the older style config. The config below should address both cases.

```sh
ngx_addon_name=ngx_http_auth_ldap_module

LDAP_REQUIRED_LIBS="-lldap"

case "$NGX_PLATFORM" in
    Darwin:*|FreeBSD:*|Linux:*|SunOS:*)
        LDAP_REQUIRED_LIBS="$LDAP_REQUIRED_LIBS -llber"
    ;;
esac

if test -n "$ngx_module_link"; then
    ngx_module_type=HTTP
    ngx_module_name=ngx_http_auth_ldap_module
    ngx_module_incs=
    ngx_module_deps=
    ngx_module_srcs="$ngx_addon_dir/ngx_http_auth_ldap_module.c"
    ngx_module_libs="$LDAP_REQUIRED_LIBS"
    . auto/module
else
    HTTP_MODULES="$HTTP_MODULES ngx_http_auth_ldap_module"
    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_auth_ldap_module.c"
    CORE_LIBS="$CORE_LIBS $LDAP_REQUIRED_LIBS"
fi
```

I've based this on the instructions [Nginx lists on their website](https://www.nginx.com/resources/wiki/extending/converting/), and the [auth_pam module](https://github.com/stogh/ngx_http_auth_pam_module/blob/2bd0b89318ba098c2d831727556ee790c49dfaac/config)'s source.

**Comment by phlegx** [comment]
@CHERTS and the others, is there any progress here, if I may ask? It would be totally awesome to see this module converted into a dynamic one!

**Pull request closed without merging**
